### ISSUE TITLE
Any plans to support Windows?

### ISSUE THREAD

**Issue by dumblob** [arminstraub/krop#10]
I find the feature set of krop quite interesting and because at my job I have to work with Windows, I'd interested whether there are any plans on supporting the Windows platform as well?

It could be possible to use an automated `*.exe` creation mechanism like some other projects (e.g. [neovim](https://github.com/neovim/neovim/releases ) uses appveyor - see the [config file](https://github.com/neovim/neovim/blob/master/appveyor.yml )).

**Comment by arminstraub** [comment]
Unfortunately, I am not familiar with Windows or how to support it.  krop is written in python, so there shouldn't be a need to compile things into an exe file.  Have you tried installing PyQt and the other required libraries on Windows?  With these libraries available, is there anything else that prevents krop from just working on Windows?

**Comment by dumblob** [comment]
I'll try installing PyQt and see whether it works or not. I'll close this for now.
