### ISSUE TITLE
--autotrim individual pages

### ISSUE THREAD

**Issue by thblt** [arminstraub/krop#12]
Hi,

Is it possible to have `--autotrim` either automatically generate a "Trim margins" crop box for each individual page, or compute the largest crop box for the full page range?  I have some very long (>1000 pages) documents I'd like to make more readable on a small screen e-reader, and i'd rather not check each crop box individually :)

Thanks!

**Comment by arminstraub** [comment]
Hi Thibault!  That's an excellent suggestion.  I have added it to the TODO list.

**Comment by arminstraub** [comment]
You are now able to call
```
krop --trim --trim-use=all file.pdf
```
to automatically create a crop box that works for all pages.  For your large documents, this will probably take a long time though!

You can already check out the code on github for this functionality.  It will be included in the next release, which is planned soon.

**Comment by homocomputeris** [comment]
@arminstraub  Is it possible to trim each page using its own selection, i.e. do not apply the same selection to all the pages?
