### ISSUE TITLE
PyCapsule_GetPointer

### ISSUE THREAD

**Issue by bsbhro** [arminstraub/krop#15]
I do get this error:
![bildschirmfoto_2018-11-24_19-22-01](https://user-images.githubusercontent.com/45314496/48971775-81132200-f01e-11e8-9eb0-13b60bf10aed.png)

**Comment by arminstraub** [comment]
It seems that PyQt and Poppler are not properly installed on your system.  You can check by running python3 and then entering the command "from popplerqt5 import Poppler".

Unfortunately, I cannot guess what might have gone wrong.  However, searching for "ValueError: PyCapsule_GetPointer called with incorrect name" does bring up a lot of results.  Maybe something in there will help you.

**Comment by bsbhro** [comment]
Hi, Thank you,
on a fresh installed notebook with Ubuntu 18.10 it works fine.

**Comment by arminstraub** [comment]
Thank you for the update!  I'm glad that krop is working for you!
