### ISSUE TITLE
Flathub support

### ISSUE THREAD

**Issue by sojusnik** [arminstraub/krop#17]
To push the popularity of this app and simplify the installation you could publish it on [Flathub](https://flathub.org) as a Flatpak.

BTW, I would totally love to see the following features from your ToDo list soon:

> Automatize splitting pages in common ways (for instance, one page into two equally sized pages)
> Specify aspect ratio of crop regions
> Clone regions (and keep them linked)

Many thanks for the work you've already done!

**Comment by v-sukt** [comment]
:+1: for this

**Comment by arminstraub** [comment]
Thank you for suggesting this!  I am not familiar with flatpaks myself, but I have no objections to you (or someone else) maintaining a flatpak package for krop.

By the way, over the last few days, I have added new code to krop for automizing splitting pages (making grids of selections) and for specifying the aspect ratio of selections.  The code is already pushed to github so you can check it out right away.  This will be part of the next release which is planned shortly :)

**Comment by felipehw** [comment]
@arminstraub ,
just to inform that I create a request at [Flathub discourse](https://discourse.flathub.org/t/krop-flatpak-request/515).

Let's see if someone takes the task.

**Comment by arminstraub** [comment]
Thank you for the heads-up and for doing that!

**Comment by felipehw** [comment]
@nbenitez did: https://flathub.org/apps/details/com.github.arminstraub.krop

At: #32 

This issue should be closed.
