### ISSUE TITLE
app-text/krop-0.5.0.ebuild depends on dev-python/python-poppler-qt4

### ISSUE THREAD

**Issue by fancywriter** [arminstraub/krop#2]
There is no such package in the portage tree any more, but there is dev-python/python-poppler-qt5, which should be fine too.
And portage has older version of this package, could it worth updating it? I found one bug here https://bugs.gentoo.org/616432

**Comment by arminstraub** [comment]
Thank you so much for pointing out that issue!  I'm not familiar with Gentoo and have just been copying the older ebuild files (now clearly outdated) to the new version.

I have now updated the ebuild file (krop-0.5.0.ebuild on the krop website) drawing from:
https://github.com/funtoo/text-kit/blob/master/app-text/krop/krop-0.4.13.5.ebuild

Would you mind checking whether that ebuild file works, or if there are other issues to be addressed?

**Comment by fancywriter** [comment]
Actually the ebuild found on your (?) site http://arminstraub.com/downloads/krop/krop-0.5.0.ebuild worked to me... the only thing I have changed is poppler-qt5 dependency.

Perhaps the one in gentoo tree is newer, I didn't check it.

**Comment by brlin-tw** [comment]
The debian package hosted on the website also depends on python3-poppler-qt4 but actually requires popplerqt5 in runtime.

Maybe the packaging is buggy?

```
Traceback (most recent call last):
  File "/usr/bin/krop", line 18, in <module>
    main()
  File "/usr/share/krop/krop/application.py", line 65, in main
    from krop.mainwindow import MainWindow
  File "/usr/share/krop/krop/mainwindow.py", line 39, in <module>
    from krop.vieweritem import ViewerItem
  File "/usr/share/krop/krop/vieweritem.py", line 24, in <module>
    raise RuntimeError(_msg)
RuntimeError: Please install popplerqt5 first.
```

**Comment by ghost** [comment]
I also encountered the same error when using krop in Linux Mint 19.

```
qt5ct: using qt5ct plugin
Traceback (most recent call last):
  File "/usr/local/bin/krop", line 18, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/krop/application.py", line 65, in main
    from krop.mainwindow import MainWindow
  File "/usr/local/lib/python2.7/dist-packages/krop/mainwindow.py", line 39, in <module>
    from krop.vieweritem import ViewerItem
  File "/usr/local/lib/python2.7/dist-packages/krop/vieweritem.py", line 24, in <module>
    raise RuntimeError(_msg)
RuntimeError: Please install popplerqt5 first.
```

**Comment by fancywriter** [comment]
Strange that you have issues with deb package - should depend on popplerqt5 according to the https://github.com/arminstraub/krop/commit/aab14cbc066a13e327c87cf3c8a1993083e76955

**Comment by brlin-tw** [comment]
> should depend on popplerqt5 according to the aab14cb

Note that the commit creates 0.5.1, which is not released as a Debian package on the website (which currently hosts 0.5.0)

**Comment by sojusnik** [comment]
Can somebody point me to v0.5.1 .deb file in order to install it on Ubuntu 18.04.
The current version can't be installed on Ubuntu due to missing dependencies:
```
$:~/Downloads$ sudo gdebi krop_0.5.0-1_all.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
Dieses Paket kann nicht installiert werden
Dependency is not satisfiable: python-poppler-qt4|python3-poppler-qt4
```

**Comment by sojusnik** [comment]
It seems that a v0.5.1 .deb file isn't released at all. @arminstraub Could you kindly do that?

**Comment by sojusnik** [comment]
After starting krop from the master branch, I also get an error:

```
$: ~/Downloads/krop$ python -m krop
Gtk-Message: 10:59:39.451: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sojusnik/Downloads/krop/krop/__main__.py", line 2, in <module>
    main()
  File "krop/application.py", line 65, in main
    from krop.mainwindow import MainWindow
  File "krop/mainwindow.py", line 39, in <module>
    from krop.vieweritem import ViewerItem
  File "krop/vieweritem.py", line 24, in <module>
    raise RuntimeError(_msg)
RuntimeError: Please install popplerqt5 first.
```
But both are already installed: 
```
libpoppler-qt5-1/bionic-updates,bionic-security,now 0.62.0-2ubuntu2.2 amd64
python3-poppler-qt5/bionic,now 0.24.2-3build3 amd64
```

**Comment by krabo0om** [comment]
~~I get the same error.~~

try `python3 -m krop`, then it will use the installed python**3**-poppler-qt5 package.

btw: nice tool, thanks!

**Comment by sojusnik** [comment]
@krabo0om Thanks!

Although this app recommends to install `python3-poppler-qt4`, you have to install `python3-poppler-qt5`, because the first package isn't present in the Ubuntu repos.

```
$ ~/Downloads/krop-master$ python3 -m krop
Traceback (most recent call last):
  File "/home/sojusnik/Downloads/krop-master/krop/vieweritem.py", line 27, in <module>
    from popplerqt4 import Poppler
ModuleNotFoundError: No module named 'popplerqt4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sojusnik/Downloads/krop-master/krop/__main__.py", line 2, in <module>
    main()
  File "/home/sojusnik/Downloads/krop-master/krop/application.py", line 65, in main
    from krop.mainwindow import MainWindow
  File "/home/sojusnik/Downloads/krop-master/krop/mainwindow.py", line 39, in <module>
    from krop.vieweritem import ViewerItem
  File "/home/sojusnik/Downloads/krop-master/krop/vieweritem.py", line 33, in <module>
    raise RuntimeError(_msg)
RuntimeError: Please install popplerqt4 first.
	On recent versions of Ubuntu, the following should do the trick:
	sudo apt-get install python-poppler-qt4
	(or, if using python3) sudo apt-get install python3-poppler-qt4
```
Don't forget to install `python3-pypdf2` too!

Nonetheless, an updated release would be great!

**Comment by arminstraub** [comment]
I have just uploaded a new version.  The corresponding Debian package should work with Ubuntu 18.04.  Sorry for the delay!

krop works with either Qt4 or Qt5 (as well as PyPDF2 or pyPdf) and either Python 2 or 3.  It depends on the distribution, for which combination packages exist.  The new Debian package works with 18.04 (and uses Python 3). For older distributions, you will need to download older packages (try version 0.5.0) or install krop in some other way.
