### ISSUE TITLE
config.py references non-namespaced sip module

### ISSUE THREAD

**Issue by rdieter** [arminstraub/krop#23]
config.py curently includes code:
krop/config.py:    import sip
krop/config.py:sip.setapi('QString', 2)
krop/config.py:sip.setapi('QVariant', 2)

Not sure it's purpose, but recent sip/PyQt5 releases use a name-spaced PyQt5.sip module instead.  So either drop this or switch to PyQt5.sip (depends if the setapi calls are really needed anymore or not)

**Comment by arminstraub** [comment]
Thank you!  This should be fixed now on github and will be included in the next release.  The reason for that code is that in python2 (I still have an old Ubuntu 14.04 in service...) needs that call in order to use the modern PyQt API.
