### ISSUE TITLE
Asking permission to publish krop on flathub

### ISSUE THREAD

**Issue by nbenitez** [arminstraub/krop#32]
Hi Armin,

[Flathub](https://flathub.org/) is a build and distribution platform for Linux apps, packaged in
a way that makes them portable and running on all major distributions.
Anyone can submit an app (we're not doing it for profit), but one of the
requirements is to reach out to the application's authors if they would
like to help with maintenance and thus making that distribution channel
considered official.

I'm volunteering to make a flatpak for _krop_ to be published in https://flathub.org/.

The usual maintenance for new releases is just changing version string and
the file checksum. The rest is done by flathub's build infraestructure.

It's understandable if you can't commit to maintaining it, I can do the new
version updates as I'm the original packager and interested in having
_krop_ on flathub, but we'd like to know **if you are not against
distributing it on Flathub in general**.

Thank you,
Nelson

**Comment by arminstraub** [comment]
Thank you for reaching out, Nelson!  I have no objections if you wish to make a package and distribute krop on flathub; unfortunately, I won't have time to participate in that myself.  (I do hope to soon have a bit of time to update krop itself.)

**Comment by nbenitez** [comment]
Already published: https://flathub.org/apps/details/com.github.arminstraub.krop

Thanks!
