### ISSUE TITLE
Issues with snap+gs, pdftk

### ISSUE THREAD

**Issue by g-steinbach** [arminstraub/krop#33]
First: I like this app, thank you.  But running in Kubuntu 20.04 (Focal):

The snap version of Krop does not see **gs** which is not a snap; the gs option is grayed out.

Krop fails - crashes - with `Could not find object` when used on a page that was excerpted from a multi-page PDF with **pdftk**, as in e.g. `pdftk in.pdf cat 35 out.pdf`.

Anyway, I installed Krop directly from Github and now it does all I want it to do, which is cutting out individual articles from NASA Tech Briefs, producing small output files.  Except now I won't know when and how to upgrade to a new version.

**Comment by arminstraub** [comment]
I am glad to hear that the version on GitHub is working as it should on 20.04!  That also suggests that the issues you describe are specific to the snap version; unfortunately, I don't know anything about how snap works (and what would have to be done to make gs visible inside a snap).  I will therefore close this issue; however, feel free to reopen it if krop itself is not behaving correctly in some way (especially if you can reproduce the crash for the GitHub version).

If the version on GitHub works for you, you could use the features on GitHub to be notified of new releases:
https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/about-notifications

**Comment by g-steinbach** [comment]
OK, I don't know how to reopen an issue but I tried the Github version of Krop on the pdftk output file, and it fails to process it with the same error message but it does _not_ crash.  I am attaching a screenshot
![KropError_20220531](https://user-images.githubusercontent.com/44328971/171271902-108b36fa-a9b4-4386-85b1-14b1419c8038.jpg)
 and the offending input file
[TB35.pdf](https://github.com/arminstraub/krop/files/8808875/TB35.pdf)
:
BTW, it would be nice if the input file name showed somewhere, e.g. in the window title?

**Comment by arminstraub** [comment]
Thank you for that update!  This appears to be an issue with the PDF file and the PyPDF2 library that krop is using in your case (not sure which of the two is at "fault").  Fortunately, with the current version of krop you can avoid this issue by instead using PyMuPdf (depending on the version of Ubuntu, you can install this via the python3-fitz or the python3-pymupdf package).  Once installed, krop automatically choose PyMuPdf (but you can select a specific cropping library using command line flags).  I hope that helps despite the horrible delay in writing back!

**Comment by arminstraub** [comment]
BTW I just pushed code to show the PDF file name in the window title as you suggested :)
